blank_issues_enabled: false

contact_links:
  - name: V-Sekai Proposals (formal) 
    url: https://github.com/V-Sekai/V-Sekai.github.io
    about: Formal V-Sekai proposals are in the V-Sekai.github.io repository.
