# MIT License

# Copyright (c) 2022 K. S. Ernest (iFire) Lee

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: "Build V-Sekai Game"

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  repository_dispatch:
    types: [check_upstream]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  CACHE_NAME: ${{github.job}}
  VSEKAI_BASE_BRANCH: main
  GODOT_MODULES_BRANCH: main
  GODOT_BRANCH: groups-4.x

concurrency:
  group: ci-macos-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  check_upstream_commits:
    runs-on: ubuntu-latest
    name: Check upstream latest commits

    steps:
    - name: Checkout main
      uses: actions/checkout@v2

    - name: Fetch upstream changes
      id: sync-godot
      uses: ivanmilov/upstream_check_new_commits@v1
      with:
        upstream_repository: v-sekai/godot
        upstream_branch: ${{env.GODOT_BRANCH}}
        target_branch: ${{env.VSEKAI_BASE_BRANCH}}

    - name: Fetch upstream changes
      id: sync-godot-modules
      uses: ivanmilov/upstream_check_new_commits@v1
      with:
        upstream_repository: v-sekai/godot-modules-groups
        upstream_branch: ${{env.GODOT_MODULES_BRANCH}}
        target_branch: ${{env.VSEKAI_BASE_BRANCH}}

  build-macos:
    runs-on: macos-12
    steps:
      - name: Install VulkanSDK
        run: |
          IFS=$'\n\t'
          # Download and install the Vulkan SDK.
          curl -L "https://sdk.lunarg.com/sdk/download/latest/mac/vulkan-sdk.dmg" -o /tmp/vulkan-sdk.dmg
          hdiutil attach /tmp/vulkan-sdk.dmg -mountpoint /Volumes/vulkan-sdk
          /Volumes/vulkan-sdk/InstallVulkan.app/Contents/MacOS/InstallVulkan \
              --accept-licenses --default-answer --confirm-command install
          hdiutil detach /Volumes/vulkan-sdk
          rm -f /tmp/vulkan-sdk.dmg

      - uses: actions/checkout@v3
        with:
          path: "godot"
          repository: "v-sekai/godot"
          ref: ${{env.GODOT_BRANCH}}

      - uses: actions/checkout@v3
        with:
          path: "modules"
          repository: "v-sekai/godot-modules-groups"
          ref: ${{env.GODOT_MODULES_BRANCH}}
          submodules: recursive

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "project"
          submodules: recursive

      - name: Load .cicd_cache directory
        uses: actions/cache@v3
        with:
          path: godot/.cicd_cache
          key: ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}-${{github.ref}}
            ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}

      - run: brew install scons

      - name: Run build
        run: |
          cd godot
          SCONS_CACHE=.cicd_cache scons optimize=speed werror=no platform=macos target=editor use_lto=no deprecated=no builtin_freetype=yes custom_modules=../modules
          cp -r misc/dist/macos_tools.app ./vsekai_macos_release_x86_64.app
          mkdir -p vsekai_macos_release_x86_64.app/Contents/MacOS
          cp bin/godot.macos.editor.x86_64  vsekai_macos_release_x86_64.app/Contents/MacOS/Godot
          chmod +x vsekai_macos_release_x86_64.app/Contents/MacOS/Godot

      # mkdir -p build/
      # rm -rf .local/share/godot/export_templates/
      # mkdir -p .local/share/godot/export_templates/
      # cd .local/share/godot/export_templates/
      # eval `sed -e "s/ = /=/" godot/version.py` && echo $major.$minor.$status > build/version.txt
      # export VERSION=`cat build/version.txt`
      # export BASE_DIR=.local/share/godot/export_templates/
      # export TEMPLATEDIR=$BASE_DIR/$VERSION/
      # mkdir -p $TEMPLATEDIR
      # cp godot/bin/macos_release_x86_64 $TEMPLATEDIR/macos_release_x86_64
      # cp godot/bin/macos_debug_x86_64 $TEMPLATEDIR/macos_debug_x86_64
      # cp build/version.txt $TEMPLATEDIR/version.txt
      # if [[ -z "${REPO_NAME}" ]]; then
      #   export GODOT_ENGINE_GAME_NAME="game_"
      # fi
      # (echo \"## AUTOGENERATED BY BUILD\"; echo \"\"; echo \"const BUILD_LABEL = \\\"$GO_PIPELINE_LABEL\\\"\"; echo \"const BUILD_DATE_STR = \\\"$(date --utc --iso=seconds)\\\"\"; echo \"const BUILD_UNIX_TIME = $(date +%s)\" ) > /v-sekai-game/project/addons/vsk_version/build_constants.gd
      # mkdir -p /v-sekai-game/build/macos_release_x86_64/ && mkdir -p project/.godot/editor && mkdir -p project/.godot/imported && chmod +x /v-sekai-game/godot/bin/linux_editor.x86_64 && XDG_DATA_HOME=.local/share/ godot/bin/macos_release_x86_64 --headless --export "Macos" build/macos_release_x86_64/${GODOT_ENGINE_GAME_NAME}macos_release_x86_64 --path project && [ -f /v-sekai-game/build/macos_release_x86_64/${GODOT_ENGINE_GAME_NAME}macos ]

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "vsekai_macos_release_x86_64.app"
          path: godot/vsekai_macos_release_x86_64.app
          retention-days: 14

      - name: v-sekai-macos-arm64
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: |
            LICENSE
            README.md
            godot/vsekai_macos_release_x86_64.app

  build-ios:
    runs-on: macos-12
    steps:
      - name: Install VulkanSDK
        run: |
          IFS=$'\n\t'
          # Download and install the Vulkan SDK.
          curl -L "https://sdk.lunarg.com/sdk/download/latest/mac/vulkan-sdk.dmg" -o /tmp/vulkan-sdk.dmg
          hdiutil attach /tmp/vulkan-sdk.dmg -mountpoint /Volumes/vulkan-sdk
          /Volumes/vulkan-sdk/InstallVulkan.app/Contents/MacOS/InstallVulkan \
              --accept-licenses --default-answer --confirm-command install
          hdiutil detach /Volumes/vulkan-sdk
          rm -f /tmp/vulkan-sdk.dmg

      - uses: actions/checkout@v3
        with:
          path: "godot"
          repository: "v-sekai/godot"
          ref: ${{env.GODOT_BRANCH}}

      - uses: actions/checkout@v3
        with:
          path: "godot-modules-groups"
          repository: "v-sekai/godot-modules-groups"
          ref: ${{env.GODOT_MODULES_BRANCH}}
          submodules: recursive

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "project"
          submodules: recursive

      - name: Load .cicd_cache directory
        uses: actions/cache@v3
        with:
          path: godot/.cicd_cache
          key: ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}-${{github.ref}}
            ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}

      - run: brew install scons

      - name: Run build
        run: |
          cd godot
          SCONS_CACHE=.cicd_cache scons optimize=speed arch=arm64 werror=no platform=ios target=editor use_lto=no deprecated=no builtin_freetype=yes custom_modules=../godot-modules-groups
          cp -r misc/dist/ios_xcode vsekai_ios_xcode
          cp bin/libgodot.ios.editor.arm64.a vsekai_ios_xcode/libgodot.ios.release.xcframework/ios-arm64/libgodot.a

      # mkdir -p build/
      # rm -rf .local/share/godot/export_templates/
      # mkdir -p .local/share/godot/export_templates/
      # cd .local/share/godot/export_templates/
      # eval `sed -e "s/ = /=/" godot/version.py` && echo $major.$minor.$status > build/version.txt
      # export VERSION=`cat build/version.txt`
      # export BASE_DIR=.local/share/godot/export_templates/
      # export TEMPLATEDIR=$BASE_DIR/$VERSION/
      # mkdir -p $TEMPLATEDIR
      # cp godot/bin/macos_release_x86_64 $TEMPLATEDIR/macos_release_x86_64
      # cp godot/bin/macos_debug_x86_64 $TEMPLATEDIR/macos_debug_x86_64
      # cp build/version.txt $TEMPLATEDIR/version.txt
      # if [[ -z "${REPO_NAME}" ]]; then
      #   export GODOT_ENGINE_GAME_NAME="game_"
      # fi
      # (echo \"## AUTOGENERATED BY BUILD\"; echo \"\"; echo \"const BUILD_LABEL = \\\"$GO_PIPELINE_LABEL\\\"\"; echo \"const BUILD_DATE_STR = \\\"$(date --utc --iso=seconds)\\\"\"; echo \"const BUILD_UNIX_TIME = $(date +%s)\" ) > /v-sekai-game/project/addons/vsk_version/build_constants.gd
      # mkdir -p /v-sekai-game/build/macos_release_x86_64/ && mkdir -p project/.godot/editor && mkdir -p project/.godot/imported && chmod +x /v-sekai-game/godot/bin/linux_editor.x86_64 && XDG_DATA_HOME=.local/share/ godot/bin/macos_release_x86_64 --headless --export "Macos" build/macos_release_x86_64/${GODOT_ENGINE_GAME_NAME}macos_release_x86_64 --path project && [ -f /v-sekai-game/build/macos_release_x86_64/${GODOT_ENGINE_GAME_NAME}macos ]

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "vsekai_ios_xcode"
          path: godot/vsekai_ios_xcode
          retention-days: 14

      - name: v-sekai-iphone-arm64
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: |
            LICENSE
            README.md
            godot/vsekai_ios_xcode

  build-linux:
    runs-on: ubuntu-18.04
    container: docker.io/groupsinfra/gocd-agent-centos-8-groups:v22.3.0groupsbash2
    steps:
      # Setup scons, print python version and scons version info, so if anything is broken it won't run the build.
      - name: Installing yum packages
        run: |
          clang++ --version
          python --version
          scons --version
          
      - uses: actions/checkout@v3
        with:
          path: "godot"
          repository: "v-sekai/godot"
          ref: ${{env.GODOT_BRANCH}}

      - uses: actions/checkout@v3
        with:
          path: "modules"
          repository: "v-sekai/godot-modules-groups"
          ref: ${{env.GODOT_MODULES_BRANCH}}
          submodules: recursive

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "project"
          submodules: recursive

      - name: Load .cicd_cache directory
        uses: actions/cache@v3
        with:
          path: godot/.cicd_cache
          key: ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}-${{github.ref}}
            ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}

      - name: Run build
        run: |
          cd godot
          export VSK_GODOT_LINUX_BSD_X86_64=godot.linuxbsd.editor.x86_64.llvm
          SCONS_CACHE=.cicd_cache scons optimize=speed werror=no platform=linuxbsd target=editor use_llvm=yes use_fastlto=no deprecated=no use_static_cpp=yes builtin_freetype=yes custom_modules=../modules          
          #cp bin/$VSK_GODOT_LINUX_BSD_X86_64 bin/linux_debug.x86_64
          #cp bin/$VSK_GODOT_LINUX_BSD_X86_64  bin/linux_editor.x86_64
          #cp bin/$VSK_GODOT_LINUX_BSD_X86_64  bin/linux_release.x86_64 && cp bin/$VSK_GODOT_LINUX_BSD_X86_64  bin/linux_release.x86_64 && strip --strip-debug bin/linux_release.x86_64
          #cp bin/$VSK_GODOT_LINUX_BSD_X86_64  bin/linux_debug.x86_64 && cp bin/$VSK_GODOT_LINUX_BSD_X86_64  bin/linux_debug.x86_64 && strip --strip-debug bin/linux_debug.x86_64  
          #mkdir -p .local/share/godot/export_templates/
          #cd .local/share/godot/export_templates/
          #eval `sed -e "s/ = /=/" /v-sekai-game/godot/version.py` && echo $major.$minor.$status > /v-sekai-game/project/build/version.txt
          #export VERSION=`cat /v-sekai-game/project/build/version.txt`
          #export BASE_DIR=/v-sekai-game/.local/share/godot/export_templates/ 
          #export TEMPLATEDIR=$BASE_DIR/$VERSION/
          #mkdir -p $TEMPLATEDIR
          #cp bin/linux_debug.x86_64 $TEMPLATEDIR/linux_debug.x86_64
          #cp bin/linux_release.x86_64 $TEMPLATEDIR/linux_release.x86_64
          #cp build/version.txt $TEMPLATEDIR/version.txt
          #if [[ -z "${REPO_NAME}" ]]; then
          #  export GODOT_ENGINE_GAME_NAME="v-sekai-game-"
          #fi
          #TODO: build version
          #(echo \"## AUTOGENERATED BY BUILD\"; echo \"\"; echo \"const BUILD_LABEL = \\\"$GO_PIPELINE_LABEL\\\"\"; echo \"const BUILD_DATE_STR = \\\"$(date --utc --iso=seconds)\\\"\"; echo \"const BUILD_UNIX_TIME = $(date +%s)\" ) > ../project/addons/vsk_version/build_constants.gd
          #End todo.
          #cp bin/linux_release.x86_64 ../build/linux_release.x86_64
          #mkdir -p ../project/build/linux_release_x86_64/
          #mkdir -p ../project/.godot/editor
          #mkdir -p ../project/.godot/imported
          #chmod +x /v-sekai-game/godot/bin/linux_editor.x86_64
          #XDG_DATA_HOME=/.local/share/ bin/linux_editor.x86_64 --headless --export-release "Linux/X11" ../linux_release_x86_64/${GODOT_ENGINE_GAME_NAME}linuxbsd --path project || [ -f linux_release_x86_64/${GODOT_ENGINE_GAME_NAME}linuxbsd ]

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: editor_linux_release_x86_64
          path: godot/bin/godot.linuxbsd.editor.x86_64.llvm
          retention-days: 14

  build-windows:
    runs-on: windows-2019
    steps:

      - uses: actions/checkout@v3
        with:
          path: "godot"
          repository: "v-sekai/godot"
          ref: ${{env.GODOT_BRANCH}}

      - uses: actions/checkout@v3
        with:
          path: "modules"
          repository: "v-sekai/godot-modules-groups"
          ref: ${{env.GODOT_MODULES_BRANCH}}
          submodules: recursive

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "project"
          submodules: recursive

      - name: Load .cicd_cache directory
        uses: actions/cache@v3
        with:
          path: godot/.cicd_cache
          key: ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}-${{github.ref}}
            ${{env.CACHE_NAME}}-${{env.VSEKAI_BASE_BRANCH}}

      # Setup scons, print python version and scons version info, so if anything is broken it won't run the build.
      - name: Configuring Python packages
        run: |
          python3 -c "import sys; print(sys.version)"
          python3 -m pip install scons
          python3 --version
          scons --version

      - name: Install llvm-mingw
        run: |
          curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20220906/llvm-mingw-20220906-ucrt-x86_64.zip
          7z x llvm-mingw-20220906-ucrt-x86_64.zip
          mv llvm-mingw-20220906-ucrt-x86_64 llvm-mingw

      - name: Run build
        shell: bash
        run: |
          cd godot
          export PATH="$PWD/../llvm-mingw/bin:$PATH"
          export VSK_GODOT_WINDOWS_X86_64=godot.windows.editor.x86_64.llvm.exe
          SCONS_CACHE=.cicd_cache scons optimize=speed werror=no platform=windows target=editor use_fastlto=no deprecated=no LINKFLAGS="-Wl,-pdb=" CCFLAGS="-Wall -Wno-tautological-compare -g -gcodeview" debug_symbols=no use_llvm=yes use_mingw=yes custom_modules=../modules
          cp bin/$VSK_GODOT_WINDOWS_X86_64 bin/windows_release_x86_64.exe 
          x86_64-w64-mingw32-strip --strip-debug bin/windows_release_x86_64.exe
          cp bin/${VSK_GODOT_WINDOWS_X86_64%.exe}.pdb bin/windows_release_x86_64.pdb
          #mkdir -p   project/build/
          #mkdir -p   .local/share/godot/export_templates/
          #cd   .local/share/godot/export_templates/
          #eval `sed -e "s/ = /=/"   godot/version.py` && echo $major.$minor.$status >   project/build/version.txt
          #export VERSION=`cat   project/build/version.txt`
          #export BASE_DIR=  .local/share/godot/export_templates/ 
          #export TEMPLATEDIR=$BASE_DIR/$VERSION/
          #mkdir -p $TEMPLATEDIR
          #cp   godot/bin/windows_release_x86_64.exe $TEMPLATEDIR/windows_release_x86_64.exe
          #cp   godot/bin/windows_release_x86_64.exe $TEMPLATEDIR/windows_debug_x86_64.exe
          #cp   project/build/version.txt $TEMPLATEDIR/version.txt
          #if [[ -z "${REPO_NAME}" ]]; then
          #  export GODOT_ENGINE_GAME_NAME="v-sekai-game-"
          #fi
          ## TODO: build version
          ## (echo \"## AUTOGENERATED BY BUILD\"; echo \"\"; echo \"const BUILD_LABEL = \\\"$GO_PIPELINE_LABEL\\\"\"; echo \"const BUILD_DATE_STR = \\\"$(date --utc --iso=seconds)\\\"\"; echo \"const BUILD_UNIX_TIME = $(date +%s)\" ) >   project/addons/vsk_version/build_constants.gd
          ## End todo.
          #cp bin/windows_release_x86_64.exe ../windows_release_x86_64.exe
          #cp bin/windows_release_x86_64.pdb ../windows_release_x86_64.pdb
          #mkdir -p ../windows_release_x86_64/ && mkdir -p ../project/.godot/editor
          #mkdir -p ../project/.godot/imported && chmod +x ../bin/linux_editor.x86_64
          #XDG_DATA_HOME=  .local/share/ bin/linux_editor.x86_64 --headless --export-release "Windows Desktop" windows_release_x86_64/${GODOT_ENGINE_GAME_NAME}windows.exe --path   project || [ -f   project/build/windows_release_x86_64/${GODOT_ENGINE_GAME_NAME}windows.exe ]
          #cp godot/bin/windows_release_x86_64.pdb ../windows_release_x86_64/${GODOT_ENGINE_GAME_NAME}windows.pdb

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: editor_windows_release_x86_64
          path: godot/bin/windows_release_x86_64.exe
          retention-days: 14

      - name: Upload Debug Symbols Artifact
        uses: actions/upload-artifact@v2
        with:
          name: editor_windows_release_x86_64_pdb
          path: godot/bin/windows_release_x86_64.pdb
          retention-days: 14
